services:
  - type: web
    name: asf
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter

    envVars:
      - key: ASF_VERSION
        sync: false

      - key: ASF_IPC_PORT
        value: "1242"

      - key: GITHUB_USERNAME
        sync: false

      - key: GITHUB_TOKEN
        sync: false

      - key: GITHUB_REPOSITORY_USERNAME
        sync: false

      - key: GITHUB_REPOSITORY_NAME
        sync: false

    disk:
      name: asf-config
      mountPath: /app/config
      sizeGB: 1
