services:
  - type: web
    name: asf
    env: docker
    dockerfile: ./Dockerfile
    plan: starter

    envVars:
      - key: ASF_VERSION
        value: ${{ secrets.ASF_VERSION }}
      - key: ASF_IPC_PORT
        value: ${{ secrets.ASF_IPC_PORT }}
      - key: GITHUB_USERNAME
        value: ${{ secrets.GITHUB_USERNAME }}
      - key: GITHUB_TOKEN
        value: ${{ secrets.GITHUB_TOKEN }}
      - key: GITHUB_REPOSITORY_USERNAME
        value: ${{ secrets.GITHUB_REPOSITORY_USERNAME }}
      - key: GITHUB_REPOSITORY_NAME
        value: ${{ secrets.GITHUB_REPOSITORY_NAME }}

    disk:
      name: asf-config
      mountPath: /app/config
      sizeGB: 1

    ports:
      - port: ${{ secrets.ASF_IPC_PORT }}
        protocol: http
